const lessons=[
{id:1,skill:'listening',level:1,prompt:'Qual frase você ouviu?',phrase:'How are you today?',pt:'Como você está hoje?',options:['How are you today?','Where are you going?','What is your name?'],tip:'“How are you?” é uma forma natural de perguntar como alguém está.'},
{id:2,skill:'writing',level:1,prompt:'Escreva em inglês',phrase:'I live in São Paulo',pt:'Eu moro em São Paulo',tip:'Use “live in” para cidades e países.'},
{id:3,skill:'speaking',level:1,prompt:'Fale esta frase em voz alta',phrase:'Nice to meet you',pt:'Prazer em conhecer você',tip:'Ligue o som de “to” com “meet”: tə-meet.'},
{id:4,skill:'listening',level:2,prompt:'Complete o que você ouviu',phrase:'I usually wake up at seven',pt:'Eu geralmente acordo às sete',options:['I usually wake up at seven','I always work until seven','I rarely wake up early'],tip:'“Usually” indica algo que acontece na maioria das vezes.'},
{id:5,skill:'writing',level:2,prompt:'Escreva em inglês',phrase:'She has been working all day',pt:'Ela está trabalhando o dia todo',tip:'“Has been” + verbo-ing enfatiza uma ação que vem acontecendo.'},
{id:6,skill:'speaking',level:2,prompt:'Responda com naturalidade',phrase:'Could you say that again, please?',pt:'Poderia dizer isso novamente, por favor?',tip:'“Could you” soa mais gentil que “Can you”.'},
{id:7,skill:'listening',level:3,prompt:'Escolha o significado mais próximo',phrase:'I would have gone if I had known',pt:'Eu teria ido se soubesse',options:['Eu teria ido se soubesse','Eu fui porque sabia','Eu irei quando souber'],tip:'“Would have” + particípio fala de algo passado que não aconteceu.'},
{id:8,skill:'writing',level:3,prompt:'Traduza com naturalidade',phrase:'I am looking forward to hearing from you',pt:'Estou ansioso para receber notícias suas',tip:'Depois de “look forward to”, use verbo com -ing.'},
{id:9,skill:'speaking',level:3,prompt:'Pratique ritmo e entonação',phrase:'As far as I know, the meeting is still on',pt:'Até onde eu sei, a reunião continua confirmada',tip:'Faça uma pausa curta depois de “know”.'}];
const initial={xp:0,streak:1,level:1,completed:0,skills:{listening:22,speaking:18,writing:24},mistakes:[],history:[12,18,14,25,20,28,32]};
let p=JSON.parse(localStorage.getItem('fluency-progress')||'null')||initial,screen='home',current=lessons[0],answer='',checked=null,recognizer=null,recorder=null,voiceChunks=[],voiceUrl='',holding=false,voiceStatus='';
const $=s=>document.querySelector(s), norm=s=>s.toLowerCase().replace(/[.,!?']/g,'').replace(/\s+/g,' ').trim();
const meta={listening:['Escuta','🎧','cyan'],speaking:['Fala','🎙️','coral'],writing:['Escrita','✍️','violet']};
function save(){localStorage.setItem('fluency-progress',JSON.stringify(p))} function weak(){return Object.entries(p.skills).sort((a,b)=>a[1]-b[1])[0][0]}
function pick(){let pool=lessons.filter(x=>Math.abs(x.level-p.level)<=1),w=weak(),weighted=[...pool.filter(x=>x.skill===w),...pool,...p.mistakes.map(id=>lessons.find(x=>x.id===id)).filter(Boolean)];return weighted[Math.floor(Math.random()*weighted.length)]}
function speak(){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(current.phrase);u.lang='en-US';u.rate=.88;speechSynthesis.speak(u)}
function start(){current=pick();answer='';checked=null;screen='lesson';render()}
function go(s){screen=s;render()}
function skillCards(){return `<section class="stats">${Object.entries(meta).map(([k,m])=>`<article class="skill ${m[2]}"><header><span>${m[1]}</span><small>+${k==='speaking'?8:k==='listening'?5:3}% esta semana</small></header><h3>${m[0]}</h3><b>${p.skills[k]}<small>/100</small></b><i><em style="width:${p.skills[k]}%"></em></i></article>`).join('')}</section>`}
function shell(content){return `<aside><button class="brand" onclick="go('home')"><span>F</span><strong>fluency<em>lab</em></strong></button><nav><button class="${screen==='home'?'active':''}" onclick="go('home')">⌂ <span>Hoje</span></button><button class="${screen==='lesson'?'active':''}" onclick="start()">▣ <span>Aprender</span></button><button class="${screen==='progress'?'active':''}" onclick="go('progress')">♕ <span>Progresso</span></button></nav><div class="streak">🔥 <b>${p.streak} dias<small>Sequência atual</small></b></div></aside><main>${content}</main><nav class="mobile"><button onclick="go('home')">⌂<small>Hoje</small></button><button onclick="start()">▣<small>Aprender</small></button><button onclick="go('progress')">♕<small>Progresso</small></button></nav>`}
function home(){let level=p.level===1?'A1 · Iniciante':p.level===2?'A2–B1 · Intermediário':'B2+ · Avançado';return shell(`<header class="top"><div><small>SEU TREINO DE HOJE</small><h1>Good morning, Wellington 👋</h1><p>Seu treino personalizado está pronto. Vamos avançar?</p></div><div class="level"><small>SEU NÍVEL</small><b>${level}</b><i><em style="width:${Math.min(100,(p.completed%6)*16+18)}%"></em></i></div></header><section class="focus"><div><small>✦ TREINO ADAPTATIVO · 12 MIN</small><h2>Fale com mais<br><em>confiança</em></h2><p>Selecionamos escuta ativa, pronúncia e escrita com base no seu desempenho.</p><div class="tags"><span>🎧 4 min</span><span>🎙️ 5 min</span><span>✍️ 3 min</span></div><button class="primary lime" onclick="start()">▶ Começar treino</button></div><div class="orbit"><i></i><b>🎙️</b><span>Speak</span><span>Listen</span></div></section><div class="title"><div><h2>Seu progresso</h2><p>O treino muda conforme você aprende.</p></div><button onclick="go('progress')">Ver detalhes →</button></div>${skillCards()}<section class="insight"><span>◎</span><div><small>INSIGHT DO DIA</small><b>Você aprende mais rápido quando fala antes de se sentir pronto.</b><p>Hoje daremos prioridade a respostas curtas em voz alta.</p></div><button onclick="start()">Praticar fala →</button></section>`)}
function lesson(){let m=meta[current.skill],input='';if(current.skill==='listening')input=`<button class="audio" onclick="speak()">🔊<span>Tocar áudio</span></button>`;if(current.skill==='writing')input=`<div class="translation">“${current.pt}”</div><textarea id="write" placeholder="Digite sua resposta em inglês…" oninput="answer=this.value;enable()">${answer}</textarea>`;if(current.skill==='speaking')input=`<div class="phrase"><b>${current.phrase}</b><span>${current.pt}</span><button onclick="speak()">🔊</button></div><p class="holdhint">Segure o botão enquanto fala e solte ao terminar</p><button class="record" aria-label="Segure para falar" oncontextmenu="return false" onpointerdown="holdStart(event)" onpointerup="holdStop(event)" onpointercancel="holdStop(event)" onkeydown="if((event.key===' '||event.key==='Enter')&&!event.repeat)holdStart(event)" onkeyup="if(event.key===' '||event.key==='Enter')holdStop(event)">🎙️<span>Segure para falar</span></button><p class="voice-status" aria-live="polite">${voiceStatus}</p>${answer?`<p class="heard">${voiceUrl?'Sua gravação foi concluída.':'Entendi:'} ${voiceUrl?'':`“${answer}”`}</p>`:''}${voiceUrl?`<audio class="voice-playback" controls src="${voiceUrl}"></audio>`:''}`;if(current.options)input+=`<div class="options">${current.options.map(o=>`<button class="${answer===o?'selected':''}" onclick="choose('${o.replaceAll("'","\\'")}')">${o}<span>${answer===o?'✓':''}</span></button>`).join('')}</div>`;let feedback=checked===null?'':`<div class="feedback ${checked?'ok':'no'}"><span>${checked?'✓':'↻'}</span><div><b>${checked?'Muito bem!':'Quase lá'}</b><p>${checked?current.tip:`Resposta sugerida: “${current.phrase}”. ${current.tip}`}</p></div></div>`;return shell(`<section class="lesson"><header><button onclick="go('home')">×</button><i><em style="width:${Math.min(92,20+p.completed%6*14)}%"></em></i><b>🔥 ${p.streak}</b></header><article><div class="exicon ${m[2]}">${m[1]}</div><small>${m[0].toUpperCase()} · NÍVEL ${current.level}</small><h1>${current.prompt}</h1>${input}${feedback}<footer>${checked===null?`<button id="check" class="primary wide" ${answer?'':'disabled'} onclick="verify()">Verificar resposta</button>`:`<button class="primary wide" onclick="next()">Continuar →</button>`}</footer></article></section>`)}
function progress(){return shell(`<section class="progress"><header><small>SEU DESENVOLVIMENTO</small><h1>Progresso que você consegue sentir.</h1><p>Medimos o que você já consegue compreender e produzir.</p></header><div class="metrics"><article>🏆 <b>${p.xp}<small>XP total</small></b></article><article>🔥 <b>${p.streak}<small>dias seguidos</small></b></article><article>✓ <b>${p.completed}<small>respostas certas</small></b></article></div><section class="chartbox"><small>EVOLUÇÃO RECENTE</small><h2>Ritmo de aprendizagem</h2><div class="chart">${p.history.map(v=>`<i style="height:${v*2.3}px"></i>`).join('')}</div></section><div class="title"><div><h2>Habilidades</h2><p>Seu próximo treino priorizará ${meta[weak()][0].toLowerCase()}.</p></div></div>${skillCards()}<button class="primary center" onclick="start()">Continuar aprendendo →</button></section>`)}
function choose(x){answer=x;render()}function enable(){let b=$('#check');if(b)b.toggleAttribute('disabled',!answer)}function next(){current=pick();answer='';checked=null;render()}
function verify(){let ok=current.skill==='speaking'?answer.length>2:norm(answer)===norm(current.phrase)||norm(answer)===norm(current.pt);checked=ok;p.xp+=ok?12:2;if(ok)p.completed++;p.level=p.completed>=12?3:p.completed>=5?2:1;p.skills[current.skill]=Math.max(5,Math.min(100,p.skills[current.skill]+(ok?4:-2)));p.mistakes=ok?p.mistakes.filter(x=>x!==current.id):[...new Set([...p.mistakes,current.id])];p.history=[...p.history.slice(-6),ok?32:12];save();render()}
function setRecordingUI(on,text){let b=$('.record');if(!b)return;b.classList.toggle('recording',on);let s=b.querySelector('span');if(s)s.textContent=text}
async function holdStart(e){e.preventDefault();if(holding)return;holding=true;voiceStatus='';voiceUrl='';answer='';if(e.pointerId!==undefined&&e.currentTarget.setPointerCapture)try{e.currentTarget.setPointerCapture(e.pointerId)}catch{}setRecordingUI(true,'Falando… solte para parar');let C=window.SpeechRecognition||window.webkitSpeechRecognition;if(C){recognizer=new C();recognizer.lang='en-US';recognizer.continuous=true;recognizer.interimResults=true;recognizer.onresult=ev=>{let text='';for(let i=0;i<ev.results.length;i++)text+=ev.results[i][0].transcript+' ';answer=text.trim();voiceStatus=answer?`Ouvindo: “${answer}”`:'Ouvindo…';let status=$('.voice-status');if(status)status.textContent=voiceStatus};recognizer.onerror=()=>{voiceStatus='Não consegui transcrever. Tente novamente.'};recognizer.onend=()=>{recognizer=null;setRecordingUI(false,'Segure para falar');if(answer)render();else{let status=$('.voice-status');if(status)status.textContent=voiceStatus||'Fale um pouco mais perto do microfone.'}};try{recognizer.start();return}catch{recognizer=null}}
try{let stream=await navigator.mediaDevices.getUserMedia({audio:true});if(!holding){stream.getTracks().forEach(t=>t.stop());return}voiceChunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=ev=>{if(ev.data.size)voiceChunks.push(ev.data)};recorder.onstop=()=>{voiceUrl=URL.createObjectURL(new Blob(voiceChunks,{type:recorder.mimeType||'audio/webm'}));stream.getTracks().forEach(t=>t.stop());recorder=null;answer='Gravação concluída';voiceStatus='Ouça sua gravação antes de continuar.';render()};recorder.start()}catch{holding=false;voiceStatus='Não foi possível acessar o microfone. Confira a permissão do navegador.';setRecordingUI(false,'Segure para falar');let status=$('.voice-status');if(status)status.textContent=voiceStatus}}
function holdStop(e){e.preventDefault();if(!holding)return;holding=false;setRecordingUI(false,'Processando…');if(recognizer)try{recognizer.stop()}catch{}if(recorder&&recorder.state==='recording')recorder.stop()}
function render(){document.getElementById('app').innerHTML=screen==='home'?home():screen==='lesson'?lesson():progress()}render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
